# Part of recaster-dfl (GPL-3.0). Copyright (C) 2026 PixelMorph LLC. See CHANGES.md.
"""QA guards for the release pipeline (REC-187 re-review).

- LockPrParityTests: open_lock_pr.sh's pre-checks (lock_pr_checks.py) must refuse
  every lock the app's lock model refuses to publish (release_problem()), so the
  owner gets the precise reason before a branch is created in the app checkout.
- WorkflowGuardTests: the env build keeps installing from the committed locks
  (conda-lock.yml via micromamba; requirements.txt with --require-hashes --no-deps).
- WorkflowModeParityTests: the env build's inputs are the same in dry-run and
  release mode, so every PR dry run rehearses the release build. No cache is
  enabled by an expression, and no cache key is passed unless its flag is a
  literal true (rdfl-2026.10.0-rc1 failed because the release set
  cache-downloads false but still passed cache-downloads-key).

The parity tests need pydantic (the vendored app lock model) and the mode tests
need PyYAML; both run in release.yml's tools job and are skipped without them
(ci.yml's bridge-tests).
"""

import json
import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "ci" / "release"))
sys.path.insert(0, str(ROOT / "ci" / "release" / "vendor"))

import lock_pr_checks as lpc  # noqa: E402

try:
    import pydantic  # noqa: F401
    HAVE_PYDANTIC = True
except ImportError:
    HAVE_PYDANTIC = False

try:
    import yaml
    HAVE_YAML = True
except ImportError:
    HAVE_YAML = False

REPO = "PixelMorphDev/recaster-dfl"
TAG = "rdfl-2026.10.0-rc1"
SHA = "c" * 40
BASE = "https://runtimes.recaster.studio"
WORKFLOW = ROOT / ".github" / "workflows" / "release.yml"


def _artifact(name, key_dir, fmt="tar.gz"):
    return {"name": name, "urls": [f"{BASE}/dfl/{key_dir}/{name}"], "sha256": "0" * 64, "size": 1,
            "unpacked_size": 1, "format": fmt}


def _lock(**overrides):
    lock = {"schema": 1, "runtime": "recaster-dfl", "tag": TAG, "placeholder": False,
            "comment": f"Generated by the recaster-dfl release CI: https://github.com/{REPO}/actions/runs/1",
            "dfl": {"repo": f"https://github.com/{REPO}", "commit": SHA, "bridge_protocol": 1,
                    "bridge_version": "1.0.0"},
            "artifacts": {"source": _artifact("src.tar.gz", TAG), "weights": _artifact("w.tar", "weights", "tar"),
                          "envs": {"macos-arm64-metal": dict(_artifact("env.tar.gz", TAG),
                                                             env_id="macos-arm64-metal-x", python="3.10")}},
            "signature": None, "signing_key_id": None}
    lock.update(overrides)
    return lock


@unittest.skipUnless(HAVE_PYDANTIC, "pydantic not installed (runs in release.yml tools job)")
class LockPrParityTests(unittest.TestCase):
    def _app_problem(self, lock):
        from recaster_app.lock_model import RuntimeLock
        return RuntimeLock.model_validate(lock).release_problem()

    def test_good_lock_passes_both(self):
        self.assertEqual(lpc.lock_problems(_lock(), TAG, SHA), [])
        self.assertIsNone(self._app_problem(_lock()))

    def test_every_dry_run_spelling_the_app_refuses_is_refused(self):
        for comment in ("dry-run build", "DRY-RUN", "dry_run", "dryrun", "Dry  Run", "dry\trun"):
            with self.subTest(comment=comment):
                lock = _lock(comment=comment)
                self.assertEqual(self._app_problem(lock), "dry-run lock")
                self.assertTrue(lpc.lock_problems(lock, TAG, SHA),
                                f"lock_pr_checks accepted a comment the app treats as a dry run: {comment!r}")

    def test_weights_prefix_is_for_weights_only(self):
        for role in ("source", "env"):
            with self.subTest(role=role):
                lock = _lock()
                art = lock["artifacts"]["source"] if role == "source" else lock["artifacts"]["envs"]["macos-arm64-metal"]
                art["urls"] = [f"{BASE}/dfl/weights/{art['name']}"]
                self.assertIsNotNone(self._app_problem(lock))
                self.assertTrue(lpc.lock_problems(lock, TAG, SHA),
                                f"lock_pr_checks accepted a {role} URL under dfl/weights/")


class WorkflowGuardTests(unittest.TestCase):
    def setUp(self):
        # Shell line continuations joined, so a multi-line run command is one line
        self.text = WORKFLOW.read_text(encoding="utf-8").replace("\\\n", " ")

    def test_conda_side_installs_from_the_conda_lock(self):
        files = [f.strip() for f in re.findall(r"environment-file:([^\n]+)", self.text)]
        self.assertEqual(files, ["envs/${{ matrix.platform }}/conda-lock.yml"])
        self.assertNotIn("environment.yml", "\n".join(l for l in self.text.splitlines()
                                                       if not l.lstrip().startswith("#")))

    def test_pip_side_is_hash_pinned_without_a_resolver(self):
        installs = [line for line in self.text.splitlines() if "pip install" in line and "requirements.txt" in line]
        self.assertEqual(len(installs), 1, installs)
        for flag in ("--require-hashes", "--no-deps", "--only-binary :all:",
                     '-r "envs/${PLATFORM}/requirements.txt"'):
            self.assertIn(flag, installs[0])


# setup-micromamba's cache enable flags (each has a <flag>-key input)
MICROMAMBA_CACHE_FLAGS = ("cache-downloads", "cache-environment")
# Anything that differs between a tag push and a dry run
MODE_EXPRESSIONS = ("outputs.release", "github.event_name", "github.ref", "github.head_ref")


def _steps(workflow):
    for job_id, job in (workflow.get("jobs") or {}).items():
        for i, step in enumerate(job.get("steps") or []):
            yield job_id, step.get("name") or step.get("uses") or f"step {i}", step


def cache_input_problems(workflow):
    """Cache inputs that could differ between dry-run and release mode, or that
    the action refuses (a key with its flag not literally true)."""
    problems = []
    micromamba_steps = 0
    for job_id, name, step in _steps(workflow):
        uses = step.get("uses") or ""
        inputs = step.get("with") or {}
        where = f"{job_id} / {name}"
        if uses.startswith("mamba-org/setup-micromamba@"):
            micromamba_steps += 1
            for flag in MICROMAMBA_CACHE_FLAGS:
                if flag in inputs and not isinstance(inputs[flag], bool):
                    problems.append(f"{where}: {flag} must be a literal true/false, not {inputs[flag]!r}")
        # Any action: a cache key needs its flag literally true (setup-micromamba
        # refuses a key with the flag false), and no cache input may be an
        # expression, which could change with the mode
        for input_name, value in inputs.items():
            if "cache" not in input_name:
                continue
            if input_name.endswith("-key"):
                flag = input_name[:-len("-key")]
                if inputs.get(flag) is not True:
                    problems.append(f"{where}: {input_name} is set but {flag} is {inputs.get(flag)!r}")
            elif isinstance(value, str) and "${{" in value:
                problems.append(f"{where}: {input_name} is an expression ({value!r})")
    if not micromamba_steps:
        problems.append("no setup-micromamba step found (the checker is looking at the wrong workflow)")
    return sorted(set(problems))


@unittest.skipUnless(HAVE_YAML, "PyYAML not installed (runs in release.yml tools job)")
class WorkflowModeParityTests(unittest.TestCase):
    def setUp(self):
        self.workflow = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))

    def test_cache_inputs_are_consistent_in_both_modes(self):
        self.assertEqual(cache_input_problems(self.workflow), [])

    def test_the_rc1_step_is_refused(self):
        # The step that failed rdfl-2026.10.0-rc1 (run 36125530274)
        rc1 = {"jobs": {"env": {"steps": [{"name": "Build the env", "uses": "mamba-org/setup-micromamba@f457c30", "with": {
            "cache-downloads": "${{ needs.meta.outputs.release != 'true' }}",
            "cache-downloads-key": "conda-pkgs-${{ matrix.platform }}",
            "cache-environment": False}}]}}}
        problems = cache_input_problems(rc1)
        self.assertTrue(any("cache-downloads must be a literal" in p for p in problems), problems)
        self.assertTrue(any("cache-downloads-key is set" in p for p in problems), problems)
        # An empty-string key (setup-micromamba reads '' as unset) is still refused: the flag isn't literal
        rc1["jobs"]["env"]["steps"][0]["with"]["cache-downloads-key"] = "${{ needs.meta.outputs.release != 'true' && 'k' || '' }}"
        self.assertTrue(cache_input_problems(rc1))

    def test_a_key_needs_a_literal_true_flag(self):
        for flags in ({}, {"cache-environment": False}):
            with self.subTest(flags=flags):
                wf = {"jobs": {"env": {"steps": [{"uses": "mamba-org/setup-micromamba@x",
                                                  "with": dict(flags, **{"cache-environment-key": "k"})}]}}}
                self.assertTrue(cache_input_problems(wf))
        ok = {"jobs": {"env": {"steps": [{"uses": "mamba-org/setup-micromamba@x",
                                          "with": {"cache-downloads": True, "cache-downloads-key": "k"}}]}}}
        self.assertEqual(cache_input_problems(ok), [])

    def test_env_build_does_not_depend_on_the_mode(self):
        # Tag, commit and retention may differ (needs.meta.outputs.tag/commit/retention);
        # nothing in the env job may branch on the release flag, the event or the ref.
        env_job = self.workflow["jobs"]["env"]
        self.assertNotIn("if", env_job)
        text = json.dumps(env_job)
        for expr in MODE_EXPRESSIONS:
            self.assertNotIn(expr, text, f"the env job references {expr}, so a dry run doesn't rehearse the release build")
        self.assertEqual(sorted(env_job["env"]), ["COMMIT", "PLATFORM", "TAG"])

    def test_the_pack_env_is_created_from_its_lock_without_a_cache_action(self):
        # The pack tool env comes from micromamba create in the conda-pack step, not a second setup-micromamba
        uses = [step.get("uses", "") for _, _, step in _steps(self.workflow)]
        self.assertEqual(sum(u.startswith("mamba-org/setup-micromamba@") for u in uses), 1)
        pack = [step["run"] for _, name, step in _steps(self.workflow) if name == "conda-pack"]
        self.assertEqual(len(pack), 1)
        self.assertIn('create -y -r "$MAMBA_ROOT_PREFIX" -n pack -f ci/release/pack-env/conda-lock.yml', pack[0])


if __name__ == "__main__":
    unittest.main()
