# Part of recaster-dfl (GPL-3.0). Copyright (C) 2026 PixelMorph LLC. See CHANGES.md.
"""QA guards for the release pipeline (REC-187 re-review).

- LockPrParityTests: open_lock_pr.sh's pre-checks (lock_pr_checks.py) must refuse
  every lock the app's lock model refuses to publish (release_problem()), so the
  owner gets the precise reason before a branch is created in the app checkout.
- WorkflowGuardTests: the env build keeps installing from the committed locks
  (conda-lock.yml via micromamba; requirements.txt with --require-hashes --no-deps).

The parity tests need pydantic (the vendored app lock model); they run in
release.yml's tools job and are skipped without it (ci.yml's bridge-tests).
"""

import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "ci" / "release"))
sys.path.insert(0, str(ROOT / "ci" / "release" / "vendor"))

import lock_pr_checks as lpc  # noqa: E402

try:
    import pydantic  # noqa: F401
    HAVE_PYDANTIC = True
except ImportError:
    HAVE_PYDANTIC = False

REPO = "PixelMorphDev/recaster-dfl"
TAG = "rdfl-2026.10.0-rc1"
SHA = "c" * 40
BASE = "https://runtimes.recaster.studio"
WORKFLOW = ROOT / ".github" / "workflows" / "release.yml"


def _artifact(name, key_dir, fmt="tar.gz"):
    return {"name": name, "urls": [f"{BASE}/dfl/{key_dir}/{name}"], "sha256": "0" * 64, "size": 1,
            "unpacked_size": 1, "format": fmt}


def _lock(**overrides):
    lock = {"schema": 1, "runtime": "recaster-dfl", "tag": TAG, "placeholder": False,
            "comment": f"Generated by the recaster-dfl release CI: https://github.com/{REPO}/actions/runs/1",
            "dfl": {"repo": f"https://github.com/{REPO}", "commit": SHA, "bridge_protocol": 1,
                    "bridge_version": "1.0.0"},
            "artifacts": {"source": _artifact("src.tar.gz", TAG), "weights": _artifact("w.tar", "weights", "tar"),
                          "envs": {"macos-arm64-metal": dict(_artifact("env.tar.gz", TAG),
                                                             env_id="macos-arm64-metal-x", python="3.10")}},
            "signature": None, "signing_key_id": None}
    lock.update(overrides)
    return lock


@unittest.skipUnless(HAVE_PYDANTIC, "pydantic not installed (runs in release.yml tools job)")
class LockPrParityTests(unittest.TestCase):
    def _app_problem(self, lock):
        from recaster_app.lock_model import RuntimeLock
        return RuntimeLock.model_validate(lock).release_problem()

    def test_good_lock_passes_both(self):
        self.assertEqual(lpc.lock_problems(_lock(), TAG, SHA), [])
        self.assertIsNone(self._app_problem(_lock()))

    def test_every_dry_run_spelling_the_app_refuses_is_refused(self):
        for comment in ("dry-run build", "DRY-RUN", "dry_run", "dryrun", "Dry  Run", "dry\trun"):
            with self.subTest(comment=comment):
                lock = _lock(comment=comment)
                self.assertEqual(self._app_problem(lock), "dry-run lock")
                self.assertTrue(lpc.lock_problems(lock, TAG, SHA),
                                f"lock_pr_checks accepted a comment the app treats as a dry run: {comment!r}")

    def test_weights_prefix_is_for_weights_only(self):
        for role in ("source", "env"):
            with self.subTest(role=role):
                lock = _lock()
                art = lock["artifacts"]["source"] if role == "source" else lock["artifacts"]["envs"]["macos-arm64-metal"]
                art["urls"] = [f"{BASE}/dfl/weights/{art['name']}"]
                self.assertIsNotNone(self._app_problem(lock))
                self.assertTrue(lpc.lock_problems(lock, TAG, SHA),
                                f"lock_pr_checks accepted a {role} URL under dfl/weights/")


class WorkflowGuardTests(unittest.TestCase):
    def setUp(self):
        # Shell line continuations joined, so a multi-line run command is one line
        self.text = WORKFLOW.read_text(encoding="utf-8").replace("\\\n", " ")

    def test_conda_side_installs_from_the_conda_lock(self):
        files = [f.strip() for f in re.findall(r"environment-file:([^\n]+)", self.text)]
        self.assertEqual(files, ["envs/${{ matrix.platform }}/conda-lock.yml"])
        self.assertNotIn("environment.yml", "\n".join(l for l in self.text.splitlines()
                                                       if not l.lstrip().startswith("#")))

    def test_pip_side_is_hash_pinned_without_a_resolver(self):
        installs = [line for line in self.text.splitlines() if "pip install" in line and "requirements.txt" in line]
        self.assertEqual(len(installs), 1, installs)
        for flag in ("--require-hashes", "--no-deps", "--only-binary :all:",
                     '-r "envs/${PLATFORM}/requirements.txt"'):
            self.assertIn(flag, installs[0])


if __name__ == "__main__":
    unittest.main()
