# Part of recaster-dfl (GPL-3.0). Copyright (C) 2026 PixelMorph LLC. See CHANGES.md.
"""Tests for ci/release/lock_pr_checks.py (what open_lock_pr.sh trusts before touching the app)."""

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "ci" / "release"))

import lock_pr_checks as lpc  # noqa: E402

REPO = "PixelMorphDev/recaster-dfl"
TAG = "rdfl-2026.10.0"
SHA = "c" * 40
BASE = "https://runtimes.recaster.studio"


def _run(**overrides):
    run = {"event": "push", "status": "completed", "conclusion": "success",
           "path": ".github/workflows/release.yml", "head_branch": TAG, "head_sha": SHA,
           "repository": {"full_name": REPO}, "head_repository": {"full_name": REPO}}
    run.update(overrides)
    return run


def _artifact(name, key_dir):
    return {"name": name, "urls": [f"{BASE}/dfl/{key_dir}/{name}"], "sha256": "0" * 64, "size": 1,
            "unpacked_size": 1, "format": "tar.gz"}


def _lock(**overrides):
    lock = {"schema": 1, "runtime": "recaster-dfl", "tag": TAG, "placeholder": False,
            "comment": f"Generated by the recaster-dfl release CI: https://github.com/{REPO}/actions/runs/1",
            "dfl": {"repo": f"https://github.com/{REPO}", "commit": SHA},
            "artifacts": {"source": _artifact("src.tar.gz", TAG), "weights": _artifact("w.tar", "weights"),
                          "envs": {"macos-arm64-metal": _artifact("env.tar.gz", TAG)}},
            "signature": None, "signing_key_id": None}
    lock.update(overrides)
    return lock


def _bytes(lock):
    return (json.dumps(lock, indent=2) + "\n").encode("utf-8")


class RunTests(unittest.TestCase):
    def test_good_run(self):
        self.assertEqual(lpc.run_problems(_run(), REPO), [])

    def test_each_run_requirement(self):
        bad = {
            "event": _run(event="pull_request"),
            "dispatch": _run(event="workflow_dispatch"),
            "conclusion": _run(conclusion="failure"),
            "in progress": _run(status="in_progress", conclusion=None),
            "workflow": _run(path=".github/workflows/ci.yml"),
            "repository": _run(repository={"full_name": "someone/recaster-dfl"}),
            "fork head": _run(head_repository={"full_name": "someone/recaster-dfl"}),
            "no head repo": _run(head_repository=None),
            "branch": _run(head_branch="main"),
        }
        for label, run in bad.items():
            with self.subTest(label):
                self.assertTrue(lpc.run_problems(run, REPO))

    def test_tag_pattern(self):
        for tag in ("rdfl-2026.10.0", "rdfl-2026.1.12", "rdfl-2026.10.0-rc1", "rdfl-2027.12.3-rc10"):
            with self.subTest(tag):
                self.assertEqual(lpc.run_problems(_run(head_branch=tag), REPO), [])
        for tag in ("rdfl-dryrun-0123456789ab", "rdfl-26.10.0", "rdfl-2026.100.0", "rdfl-2026.10",
                    "rdfl-2026.10.0-beta", "rdfl-2026.10.0-rc", "rdfl-2026.10.0\n", "xrdfl-2026.10.0",
                    "rdfl-2026.10.0/../x", "rdfl-２０２６.10.0"):
            with self.subTest(tag):
                self.assertTrue(lpc.run_problems(_run(head_branch=tag), REPO))


class LockTests(unittest.TestCase):
    def test_good_lock(self):
        self.assertEqual(lpc.lock_problems(_lock(), TAG, SHA), [])

    def test_dry_run_comment_rejected(self):
        lock = _lock(comment="DRY RUN (pull_request): nothing is published at these URLs.")
        self.assertTrue(any("DRY RUN" in p for p in lpc.lock_problems(lock, TAG, SHA)))

    def test_tag_commit_and_placeholder(self):
        self.assertTrue(lpc.lock_problems(_lock(tag="rdfl-2026.9.0"), TAG, SHA))
        self.assertTrue(lpc.lock_problems(_lock(placeholder=True), TAG, SHA))
        self.assertTrue(lpc.lock_problems(_lock(), TAG, "d" * 40))

    def test_urls_must_be_under_the_tag_or_weights(self):
        bad_urls = [
            "https://evil.example/dfl/rdfl-2026.10.0/env.tar.gz",
            f"{BASE}/dfl/rdfl-2026.9.0/env.tar.gz",
            f"{BASE}/dfl/rdfl-dryrun-0123456789ab/env.tar.gz",
            f"{BASE}/other/env.tar.gz",
            f"{BASE}/dfl/{TAG}/sub/env.tar.gz",
            f"{BASE}/dfl/{TAG}/other.tar.gz",
            f"http://runtimes.recaster.studio/dfl/{TAG}/env.tar.gz",
            f"{BASE}.evil.example/dfl/{TAG}/env.tar.gz",
        ]
        for url in bad_urls:
            with self.subTest(url):
                lock = _lock()
                lock["artifacts"]["envs"]["macos-arm64-metal"]["urls"] = [f"{BASE}/dfl/{TAG}/env.tar.gz", url]
                self.assertTrue(lpc.lock_problems(lock, TAG, SHA))
        lock = _lock()
        lock["artifacts"]["source"]["urls"] = []
        self.assertTrue(lpc.lock_problems(lock, TAG, SHA))


class CheckTests(unittest.TestCase):
    def test_published_copy_must_be_byte_identical(self):
        data = _bytes(_lock())
        fetched = []

        def fetcher(url):
            fetched.append(url)
            return data

        self.assertEqual(lpc.check(_run(), data, REPO, fetcher=fetcher), (TAG, []))
        self.assertEqual(fetched, [f"{BASE}/dfl/{TAG}/dfl_runtime.lock.json"])
        tag, problems = lpc.check(_run(), data, REPO, fetcher=lambda url: data.replace(b"\n", b"\r\n"))
        self.assertTrue(problems and "differs" in problems[0])

    def test_fetch_failure_is_a_problem(self):
        def fetcher(url):
            raise OSError("HTTP Error 404: Not Found")
        _tag, problems = lpc.check(_run(), _bytes(_lock()), REPO, fetcher=fetcher)
        self.assertTrue(problems and "could not fetch" in problems[0])

    def test_bad_run_is_rejected_before_any_fetch(self):
        def fetcher(url):
            raise AssertionError("fetched")
        tag, problems = lpc.check(_run(event="pull_request"), _bytes(_lock()), REPO, fetcher=fetcher)
        self.assertIsNone(tag)
        self.assertTrue(problems)
        _tag, problems = lpc.check(_run(), _bytes(_lock(comment="DRY RUN")), REPO, fetcher=fetcher)
        self.assertTrue(problems)

    def test_cli_rejects_a_dry_run_lock(self):
        tmp = Path(tempfile.mkdtemp())
        (tmp / "run.json").write_text(json.dumps(_run()))
        (tmp / "lock.json").write_bytes(_bytes(_lock(comment="DRY RUN (workflow_dispatch)")))
        proc = subprocess.run([sys.executable, str(ROOT / "ci" / "release" / "lock_pr_checks.py"), "--repo", REPO,
                               "--run", str(tmp / "run.json"), "--lock", str(tmp / "lock.json")],
                              capture_output=True, text=True)
        self.assertEqual(proc.returncode, 1)
        self.assertEqual(proc.stdout, "")
        self.assertIn("DRY RUN", proc.stderr)


if __name__ == "__main__":
    unittest.main()
