#!/usr/bin/env bash
# Part of recaster-dfl (GPL-3.0). Copyright (C) 2026 PixelMorph LLC. See CHANGES.md.
#
# Open the Recaster PR that updates dfl_desktop/resources/dfl_runtime.lock.json
# from a *published* release run:
#   ci/release/open_lock_pr.sh <run-id> <path-to-recaster-checkout>
#
# Runs on the owner's machine with `gh` logged in (the fork's CI has no token
# for the private app repo), from a recaster-dfl checkout. It trusts nothing
# about the run it is given until lock_pr_checks.py has confirmed that:
# - the run is a successful tag push of .github/workflows/release.yml in
#   PixelMorphDev/recaster-dfl, for an rdfl-YYYY.M.P[-rcN] tag
# - its `dfl-runtime-lock-published` artifact (uploaded only by the publish
#   job, after every object is on R2) is for that tag and commit, is not a
#   dry run, and points only at runtimes.recaster.studio/dfl/<tag>/ and
#   /dfl/weights/
# - the public dfl/<tag>/dfl_runtime.lock.json is byte-identical to it
# Then it validates the lock with the checkout's own lock model, checks that
# each URL answers with the expected size, branches from origin/main, runs
# the bundled-lock test and opens the PR.
set -euo pipefail

run_id="$1"
app="$(cd "$2" && pwd)"
here="$(cd "$(dirname "$0")" && pwd)"
fork_repo="PixelMorphDev/recaster-dfl"
case "$run_id" in ''|*[!0-9]*) echo "error: run id must be numeric" >&2; exit 1;; esac
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

gh api "repos/${fork_repo}/actions/runs/${run_id}" > "$work/run.json"
gh run download "$run_id" -R "$fork_repo" -n dfl-runtime-lock-published -D "$work/artifact"
lock="$work/artifact/dfl_runtime.lock.json"
tag="$(python3 "$here/lock_pr_checks.py" --repo "$fork_repo" --run "$work/run.json" --lock "$lock")"

cd "$app"
python3 - "$lock" <<'PY'
import json, sys, urllib.request
from dfl_desktop.dfl.lock_model import load_lock
lock = load_lock(sys.argv[1])
if lock.placeholder:
    sys.exit("the lock is a placeholder")
items = [lock.artifacts.source, lock.artifacts.weights, *lock.artifacts.envs.values()]
for a in items:
    for url in a.urls:
        req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "Recaster/lock-pr"})
        with urllib.request.urlopen(req, timeout=30) as r:
            size = int(r.headers.get("Content-Length", -1))
        if size != a.size:
            sys.exit(f"{url}: Content-Length {size}, the lock says {a.size}")
        print(f"ok {url} ({size} bytes)")
print(f"lock {lock.tag} valid for: {', '.join(lock.artifacts.envs)}")
PY

branch="chore/dfl-runtime-lock-${tag}"
git fetch origin main
git switch -c "$branch" origin/main
cp "$lock" dfl_desktop/resources/dfl_runtime.lock.json
python3 -m pytest tests/unit/dfl/test_lock_bundled_valid.py -q
git add dfl_desktop/resources/dfl_runtime.lock.json
git commit -m "chore(dfl): runtime lock for ${tag}

Generated by the recaster-dfl release run
https://github.com/${fork_repo}/actions/runs/${run_id}"
git push -u origin "$branch"
gh pr create --base main --head "$branch" --title "chore(dfl): runtime lock for ${tag}" \
  --body "Updates \`dfl_desktop/resources/dfl_runtime.lock.json\` to the published recaster-dfl runtime \`${tag}\`.

Release run: https://github.com/${fork_repo}/actions/runs/${run_id}
Every artifact URL answered HEAD with the lock's size; the lock validates with \`lock_model.py\`."
